### ISSUE TITLE
Test Infra Failure

### ISSUE THREAD

**Issue by nromito** [sharand/event-logs#1]
```
Error: HTML report not present, please check nohup.out for install error
nromito-mbp:event-logs nromito$ ls
Dockerfile         README.md          app.js             docker-compose.yml nohup.out          run.sh             splitter
LICENSE            agent              app.ts             filecompare.py     package-lock.json  sample_outputs     target
nromito-mbp:event-logs nromito$ cat nohup.out
Network event-logs_node-vnet  Creating
Network event-logs_node-vnet  Created
Network event-logs_default  Creating
Network event-logs_default  Created
Container target_1  Creating
Container target_2  Creating
Container target_2  Created
Container target_1  Created
Container splitter  Creating
Container splitter  Created
Container agent  Creating
Container agent  Created
Container filecompare  Creating
Container filecompare  Created
Container target_1  Starting
Container target_2  Starting
Container target_1  Started
Container target_2  Started
Container splitter  Starting
Container splitter  Started
Container agent  Starting
Container agent  Started
Container filecompare  Starting
Container filecompare  Started
```

Everything appears to have ran fine, but I didn't get the output of the tests

**Comment by nromito** [comment]
Running docker compose directly, I can see the agent and filecompare are flapping:
```
nromito-mbp:event-logs nromito$ docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "event-logs_node-vnet" with driver "bridge"
Creating target_2 ... done
Creating target_1 ... done
Creating splitter ... done
Creating agent    ... done
Creating filecompare ... done
Attaching to target_2, target_1, splitter, agent, filecompare
agent          | My hostname is: 736ccb86cb60
splitter       | My hostname is: b0fa409e5191
splitter       | working as splitter
agent          | Usage: node /usr/src/app/app.js <config_dir>
target_2       | My hostname is: 61d12b08f0d2
target_2       | working as target
target_2       | outputfile events.log
target_2       | App listening on port 9997
splitter       | targets [ { host: 'target_1', port: 9997 }, { host: 'target_2', port: 9997 } ]
target_1       | My hostname is: 7f9fd2603302
target_1       | working as target
splitter       | App listening on port 9997
target_1       | outputfile events.log
target_1       | App listening on port 9997
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
agent exited with code 1
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
agent          | My hostname is: 736ccb86cb60
agent          | Usage: node /usr/src/app/app.js <config_dir>
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
agent          | My hostname is: 736ccb86cb60
agent          | Usage: node /usr/src/app/app.js <config_dir>
agent exited with code 1
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
agent          | My hostname is: 736ccb86cb60
agent          | Usage: node /usr/src/app/app.js <config_dir>
agent exited with code 1
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
agent          | My hostname is: 736ccb86cb60
agent          | Usage: node /usr/src/app/app.js <config_dir>
agent exited with code 1
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
agent          | My hostname is: 736ccb86cb60
agent          | Usage: node /usr/src/app/app.js <config_dir>
agent exited with code 1
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
agent          | My hostname is: 736ccb86cb60
agent          | Usage: node /usr/src/app/app.js <config_dir>
agent exited with code 1
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
agent          | Usage: node /usr/src/app/app.js <config_dir>
agent          | My hostname is: 736ccb86cb60
agent exited with code 1
filecompare    | Traceback (most recent call last):
filecompare    |   File "filecompare.py", line 7, in <module>
filecompare    |     with open('events.log', 'r') as file1:
filecompare    | FileNotFoundError: [Errno 2] No such file or directory: 'events.log'
filecompare exited with code 1
```

**Comment by sharand** [comment]
Hi Nick, Can you please execute the solution with `./run.sh install` this will take care of building the docker image and start the install the containers as well. I also checked in my recent run results inside the sample output directory with file name `recent-run.-sh-install.log` which include building the image from scratch and creates the report.  Please let me know if you run into any other issue.

Also may i know which operating system you are trying the solution with, from the docker compose log file above it looks like the app stack is coming up successfully but the volume mount when the `events.log` file getting written is having some issue. 
Please make sure the local docker has access to your file system to mount directories sometimes it is prevent in Mac privacy settings.

**Comment by nromito** [comment]
@sharand my first run i did with `./run.sh install` which failed and didn't provide any error logs. 

Running the docker compose manually resulted in the agent to flap up and down.

I'm running on macos and also using docker 3.3.3. I don't believe its a permissions issue as I have mounted directories in the past using docker/docker-compose

**Comment by sharand** [comment]
Hi Nick, I found the issue, when I copied my code from my icloud account - since the original log file was big it was not copied and only the reference was copied. Since the input was not correct it was not generating the output file `events.log`

![image](https://user-images.githubusercontent.com/8002203/123169787-98148d80-d42e-11eb-9d40-c8c6e98a33ac.png)

I just downloaded and checked into the repo with original `large_1M_events.log` file, please just confirm once again in your at the path `event-logs/agent/inputs/large_1M_events.log`  the file is present and the size of file is ~28MB before executing `./run.sh install` or `docker compose up` 

Please see checkin log below and pull the latest or manually copy the original log file if you have in local to the agents/inputs directory

`Shans-MacBook-Air:event-logs Shan$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   agent/inputs/.DS_Store
	deleted:    agent/inputs/.large_1M_events.log.icloud
	new file:   agent/inputs/large_1M_events.log
	new file:   nohup.out

Shans-MacBook-Air:event-logs Shan$ git commit -m "original log file updated"
[main 89f44f4] original log file updated
 Committer: Shan <Shan@Shans-MacBook-Air.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 4 files changed, 1000029 insertions(+)
 create mode 100644 agent/inputs/.DS_Store
 delete mode 100644 agent/inputs/.large_1M_events.log.icloud
 create mode 100644 agent/inputs/large_1M_events.log
 create mode 100644 nohup.out
Shans-MacBook-Air:event-logs Shan$ git push
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 2.53 MiB | 475.00 KiB/s, done.
Total 7 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/sharand/event-logs.git
   9eac376..89f44f4  main -> main`

**Comment by nromito** [comment]
![image](https://user-images.githubusercontent.com/1883066/123177564-20089080-d44b-11eb-83da-e7aa543656aa.png)
Looks good now! thanks!
